import type { ReportInput, TspFundBalance } from "./types";

export const DEFAULT_TSP_RETURN_RATES: Record<string, number> = {
  G: 0.025,
  F: 0.04,
  C: 0.10,
  S: 0.11,
  I: 0.08,
  L: 0.07,
};

function makeTspFundBalances(): TspFundBalance[] {
  return [
    { fund: "G", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.G },
    { fund: "F", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.F },
    { fund: "C", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.C },
    { fund: "S", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.S },
    { fund: "I", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.I },
    { fund: "L", balance: 0, returnRate: DEFAULT_TSP_RETURN_RATES.L },
  ];
}

export const defaultReportInput: ReportInput = {
  personal: {
    fullName: "",
    dateOfBirth: "",
    address: "",
    maritalStatus: "SINGLE",
    spouseDateOfBirth: "",
  },
  employment: {
    serviceComputationDate: "",
    retirementSystem: "FERS",
    employeeType: "REGULAR",
    currentAnnualSalary: 0,
    annualSalaryIncreaseRate: 0.02,
    creditableServiceYears: 0,
    creditableServiceMonths: 0,
    sickLeaveHours: 0,
    plannedRetirementDate: "",
    csrsServiceYears: 0,
    csrsServiceMonths: 0,
    fersServiceYears: 0,
    fersServiceMonths: 0,
  },
  tsp: {
    traditionalBalances: makeTspFundBalances(),
    rothBalances: makeTspFundBalances(),
    annualContributionTraditional: 0,
    annualContributionRoth: 0,
    governmentMatchPercent: 5,
    catchUpContribution: 0,
    expectedReturnRate: 0.07,
    plannedWithdrawalAge: 62,
    withdrawalMethod: "MONTHLY_PAYMENTS",
    monthlyWithdrawalAmount: 0,
  },
  fegli: {
    basicCoverage: true,
    optionA: false,
    optionB: false,
    optionBMultiple: 1,
    optionC: false,
    optionCMultiple: 1,
    postRetirementReduction: "75_PERCENT",
  },
  fehb: {
    currentPlanName: "",
    enrollment: "SELF_ONLY",
    biweeklyPremium: 0,
    premiumIncreaseRate: 0.05,
  },
  socialSecurity: {
    estimatedBenefitAge62: 0,
    estimatedBenefitFRA: 0,
    plannedStartAge: 67,
  },
  ltc: {
    enrolled: false,
    currentPremium: 0,
    dailyBenefitAmount: 0,
    benefitPeriodYears: 3,
  },
  otherIncome: {
    otherPensions: 0,
    spouseIncome: 0,
    rentalIncome: 0,
    investmentIncome: 0,
    otherTaxableIncome: 0,
    otherNonTaxableIncome: 0,
  },
  expenses: {
    housing: 0,
    utilities: 0,
    transportation: 0,
    food: 0,
    healthcareOutOfPocket: 0,
    insurance: 0,
    debtPayments: 0,
    entertainment: 0,
    travel: 0,
    charitableGiving: 0,
    other: 0,
  },
  tax: {
    filingStatus: "SINGLE",
    federalTaxRate: 0.22,
    stateOfResidence: "",
    stateTaxRate: 0.05,
  },
  military: {
    hasMilitaryService: false,
    branch: "",
    activeDutyStartDate: "",
    activeDutyEndDate: "",
    depositPaid: false,
    depositAmountOwed: 0,
  },
  deposits: {
    hasNonDeductionService: false,
    depositOwed: 0,
    hasRefundedService: false,
    reDepositOwed: 0,
  },
  advisorName: "",
  advisorCompany: "CapitalWealth.com",
  advisorPhone: "",
  advisorEmail: "",
  colaAssumption: 0.02,
  projectionYears: 30,
};
